// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDhSZMin9jwBjdBLlhOJplS-8sCq0vCrs',
    appId: '1:714944573916:web:d04005e981b5a13871df19',
    messagingSenderId: '714944573916',
    projectId: 'seschat-a86ac',
    authDomain: 'seschat-a86ac.firebaseapp.com',
    storageBucket: 'seschat-a86ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0SPc85FaPRsiFH8WxtVEdl2pVd3eTo2c',
    appId: '1:714944573916:android:4cc899903e34ef1171df19',
    messagingSenderId: '714944573916',
    projectId: 'seschat-a86ac',
    storageBucket: 'seschat-a86ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvlVJySluqfj2E1F5djwqueAYNQeBgXlY',
    appId: '1:714944573916:ios:9dc248a1878d738271df19',
    messagingSenderId: '714944573916',
    projectId: 'seschat-a86ac',
    storageBucket: 'seschat-a86ac.firebasestorage.app',
    iosBundleId: 'com.example.sesChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvlVJySluqfj2E1F5djwqueAYNQeBgXlY',
    appId: '1:714944573916:ios:9dc248a1878d738271df19',
    messagingSenderId: '714944573916',
    projectId: 'seschat-a86ac',
    storageBucket: 'seschat-a86ac.firebasestorage.app',
    iosBundleId: 'com.example.sesChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDhSZMin9jwBjdBLlhOJplS-8sCq0vCrs',
    appId: '1:714944573916:web:07dfa9b24cfc888b71df19',
    messagingSenderId: '714944573916',
    projectId: 'seschat-a86ac',
    authDomain: 'seschat-a86ac.firebaseapp.com',
    storageBucket: 'seschat-a86ac.firebasestorage.app',
  );
}
